server:
  port: 8081

#Mybatis 控制台打印SQL语句
logging:
  level:
    com.lcb.springcloud.learning: debug

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver                      # mysql驱动包
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=UTC    # 数据库名称
    username: root
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
    #schema: classpath:sql/schema-mysql.sql                  #自动执行建表sql脚本，如果有多个sql文件，可以用逗号分隔
    #data: classpath:sql/data-mysql.sql                      #自动执行初始化sql脚本
    #initialization-mode: always                             #Spring Boot2.x 必须添加 initialization-mode配置才会执行，默认为EMBEDDED也就是嵌入式数据库（H2这种），如果要在mysql下执行需要设置成为always

  ## Redis 配置
  redis:
    database: 1             # Redis数据库索引（默认为0）
    host: 127.0.0.1         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: 123456        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 8
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 10
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
    timeout: 1200         # 连接超时时间（毫秒）

